project:
  type: website
  output-dir: docs

website:
  favicon: images/aidansitelogo2.png
  navbar:
   title: "Aidan Robertson"
   logo: images/aidansitelogo.png
   right:
      - href: index.qmd
        text: Home
      - text: Research
        href: research.qmd
      - text: Projects
        href: posts.qmd
      - text: Fieldwork
        href: fieldwork.qmd
      - text: CV
        href: https://drive.google.com/file/d/1_E1vP0ab80XiTt3xg7NPmQwO4d6nfOzp/view?usp=sharing
      - icon: github
        href: https://github.com/aidan-robertson
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/am-robertson/
        target: _blank
  page-footer:
    background: dark
    left: Aidan Robertson, {{< fa regular copyright >}} 2025
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/aidan-robertson/aidanrobertsonsite){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}, and [Quarto](https://quarto.org/){target=_blank}
  
format:
  html:
    theme:
      - styles.scss
    mainfont: Sen
    toc: true
    page-layout: full

editor: visual

