---
title: "Senior Thesis"
---

## Abstract

Coastal sage scrub is a largely degraded and threatened plant community in California. Most of its former range has been subjected to urban development, agriculture, and non-native grass invasion. This thesis seeks to compare coastal sage scrub restoration strategies, using prescribed fire, grass-specific herbicide (Clethodim), thatch clearing, and two wildflower seeding rates in a field experiment to determine the most effective combination in increasing native cover and decreasing non-native cover. The wildflower seeding rates measured three coastal sage scrub wildflowers: redmaids (*Calandrinia menzisii*), distant phacelia (*Phacelia distans*), and winecup clarkia (*Clarkia purpurea*). This thesis also examines the effect of variations in heat exposure time and fire temperature on two non-native forbs, scarlet pimpernel (*Lysimachia arvensis*) and windmill pink (*Silene gallica*), in a controlled germination experiment to understand how to best implement controlled burns to create a resilient restoration site.



## Background & Study Site

## Research Question & Hypothesis

## Initial Data Visualization

## Thesis Draft

### Introduction & Literature Review

<embed src="images/Robertson_Aidan_SIP_CV.pdf" width="800px" height="2100px"/>
